### ISSUE TITLE
Open links in same window (rather than new tab)

### ISSUE THREAD

**Issue by hasinasi** [te-online/files_linkeditor#10]
I find these links quite useful even to jump to different folders within the cloud. For that it would be useful to have some kind of option that would for all links to be opened in the same page (rather than opening a new window/tab for every link).

**Comment by te-online** [comment]
Thanks for your input. I'll look into adding this as a checkbox to the edit dialogue and saving it as meta within the file. I don't know if there is a standard-compliant way, yet.
