### ISSUE TITLE
undesired conversion of % character

### ISSUE THREAD

**Issue by fimholz** [te-online/files_linkeditor#13]
Link Editor 1.0.4

If i paste a link, e.g. to a public Google Calendar, the "%" character seems to be converted to hex format.

What I want:
`...7pe0o300%40group.calendar.com/public/basic.ics` (note: %40)

What I get, reading the Link from Nextcloud: 
`...7pe0o300%252540group.calendar.com/public/basic.ics` (note: %252540)

What I get, reading the Link directly from the file:
`...7pe0o300%2540group.calendar.com/public/basic.ics` (note: %2540)

Can someone confirm this?

**Comment by te-online** [comment]
Thanks for the report, I'll look into this as soon as I can.

**Comment by te-online** [comment]
Should be fixed in the latest release 1.0.5.
Can you test again?

(I also took first steps to add js-tests to avoid such things in the future...)

**Comment by fimholz** [comment]
It seems to work, thank you! :+1:
