### ISSUE TITLE
Browser sync

### ISSUE THREAD

**Issue by marcelklehr** [te-online/files_linkeditor#16]
Hey @te-online,

This is promising stuff! I've working on the bookmarks app thus far, but my main concern has been to sync browser data. Thus I've created https://github.com/marcelklehr/floccus

As floccus supports pluggable backends, it might be cool, to support your app as a synchronization backend as well. Just thinking out loud, as we've had people complain about missing folders in the bookmarks app.

Cheers!

**Comment by te-online** [comment]
Hey @marcelklehr! Thanks for sharing floccus and your idea for the link editor app.
Could you tell me a bit more about what file types floccus saves your bookmarks in? Is it a format that's readable by the link editor?

**Comment by marcelklehr** [comment]
Currently, floccus stores links in an XBEL file. But it's possible to add custom backend adapters that store the bookmarks in a different way, so the burden is currently on the side of floccus to implement the system your app is able to read. How does that work?

**Comment by te-online** [comment]
> XBEL
That looks like a nice format. Is there – by any chance – a JavaScript parser for that format? If so, I could easily incorporate it into the files that can be viewed and edited by the linkeditor app. (However, it would probably only be possible to edit the URL itself.) 

Oh, I just saw, you can save multiple bookmarks within one file... That makes it a bit more complicated 🤔 

> How does that work?
The linkeditor app can view and edit .URL (Windows) and .webloc (Mac) files residing in any of your nextcloud folders. Both formats are highly underspecified, so I can't provide you with an RFC or something. Basically the app only view and edits the URL itself, no metadata.

**Comment by te-online** [comment]
To keep the scope of this app small, I'd like to refrain from adding a "bookmarks" feature at this point.

Feel free to continue the discussion here, however, and also to recommend 3rd-party tools that can solve your needs.
