### ISSUE TITLE
Open link when sharing

### ISSUE THREAD

**Issue by ljalg** [te-online/files_linkeditor#19]
Thank you for developing this plugin.  One enhancement request I have is; when I share a URL link the person viewing the link can only download the file, they do not have the option to follow the link.

It may seem odd to submit this type of request as we are providing a link to a link, but we are hoping to use NextCloud for security checking to ensure the viewer has the proper permissions to access the link.

Thank you,

Louis

**Comment by te-online** [comment]
Hi Louis,

sharing links should works as you expect, maybe something's broken. I'll have a look and be back with an answer :-)


Thomas

**Comment by te-online** [comment]
Okay, now I see what you're referring to. When you share a single file which happens to be a link file it will only give you the option to download that file, opposed to when you share link files within a folder, where they can opened as always. Let me look into adding a different button to allow following the link.

**Comment by ljalg** [comment]
Thanks, I look forward to your next update.

Louis

**Comment by te-online** [comment]
Should be fixed by v1.0.8. Could you try again? 😊

**Comment by ljalg** [comment]
Great, thanks for being so responsive.  We will update our dev instance and I'll try it out.  I'll let you know how it turns out.

**Comment by ljalg** [comment]
Great, it works as I asked, but of course there are things I didn't think about (I don't mean to sound ungrateful):
Right now it's a 2 step process, hit the "view link" button and then again the "visit link" button, could that be modified to be a single click process with the verbiage "visit link"?  If it's a security issue to ensure the user understands they are navigating to a separate web site, maybe a warning text could display below the first button?

Thank you,

Louis

**Comment by te-online** [comment]
Hi Louis,

Sure, no worries – what you're describing is already in the process of being built 😉 
See https://github.com/te-online/files_linkeditor/issues/11 for some background.

I expect that we'll have the option of directly opening links without confirmation within the next weeks.

– Thomas

**Comment by ljalg** [comment]
Great, thanks.

Louis

**Comment by reiner-text** [comment]
I had to hide the "View link" button via CSS because it also was seen on a sharing page of a single audio file. Must this be that way or have I made something wrong?

**Comment by te-online** [comment]
This might be a bug - thanks for sending it in, I'll look into it as soon as possible!

On Dec 18, 2018 19:53, Reiner Text <notifications@github.com> wrote:

I had to hide the "View link" button via CSS because it also was seen on a sharing page of a single audio file. Must this be that way or have I made something wrong?

-

**Comment by te-online** [comment]
@reiner-text New release with a fix is out and should be available in your nextcloud soon.

**Comment by reiner-text** [comment]
@te-online Thanks for fixing this so quickly! I can confirm that it works and shared link files (``.url`` in my case) are visible correctly.
