### ISSUE TITLE
Nextcloud 15 compatibility

### ISSUE THREAD

**Issue by violoncelloch** [te-online/files_linkeditor#21]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by te-online** [comment]
Yes, that is definitively on the roadmap for this week, sorry for the inconvenience!

**Comment by violoncelloch** [comment]
great to hear, thank you!

**Comment by te-online** [comment]
Should be fixed by v1.0.8. Can you please test it, once it gets available for your nextcloud instance? 😊
