### ISSUE TITLE
List this app also in category Files

### ISSUE THREAD

**Issue by rasos** [te-online/files_linkeditor#24]
Thank you for this useful App. I suggest you publish it also in the `Files` category of the app store https://github.com/nextcloud/server/issues/16520#issuecomment-514495091 .

**Comment by te-online** [comment]
Thanks for your suggestion, that is a very good idea. Could you prepare a pull request, adjusting the categories in `appinfo/info.xml`? 😉

**Comment by te-online** [comment]
Looks like this category is already applied :-)
