### ISSUE TITLE
NC17 compatibility

### ISSUE THREAD

**Issue by herrmannsdorfer** [te-online/files_linkeditor#27]
Link Editor 1.0.10 does not seem NC 17 ready. The NC updater is missing an update. I am running NC 16.0.5:

![Bildschirmfoto 2019-09-30 um 10 44 18](https://user-images.githubusercontent.com/43957716/65863118-d5d6a600-e36f-11e9-9b68-3efe12345bee.png)

**Comment by te-online** [comment]
@herrmannsdorfer Thanks for reporting!
I just checked compatibility with version 17 and released v1.0.11. Can you test if this version shows up as compatible?

**Comment by schniepp** [comment]
It works here! Thank you so much!
