### ISSUE TITLE
Can't install/download this app

### ISSUE THREAD

**Issue by manu-p** [te-online/files_linkeditor#30]
Hi, no way to download/install this app:

>  Server error: `GET https://github.com/te-online/nextcloud-app-releases/raw/master/files_linkeditor/v1.0.13/files_linkeditor.tar.gz` resulted in a `500 Internal Server Error` response: 500: Internal Server Error

**Comment by alemorbel** [comment]
Github is partially down right now, wait untill the problems have been fixed, you can check the progress at [githubstatus.com](https://www.githubstatus.com/)

**Comment by te-online** [comment]
Seems to work again.

**Comment by manu-p** [comment]
Yep, fine! thanks
