### ISSUE TITLE
Incorrect link processing

### ISSUE THREAD

**Issue by ostasevych** [te-online/files_linkeditor#31]
Not working properly.

1. I create a link to https://google.ua
![image](https://user-images.githubusercontent.com/5199030/79898251-a1adfa00-8413-11ea-8172-07af50cec5ea.png)

2. When trying to open I obtain error.
![image](https://user-images.githubusercontent.com/5199030/79898315-bee2c880-8413-11ea-9fc8-55007dbbf541.png)

NC 19 beta2

**Comment by te-online** [comment]
Hi @ostasevych 

Thanks for reporting. I just checked-out Nextcloud 19 beta 2 locally and was able to create the link file you describe just fine. Can you try clicking the 3-dot menu of the link file, click edit and try saving the correct link once again? Let me know if it works.

**Comment by ostasevych** [comment]
Hi again! Me too, I checked again and it is not working :( NC 19.0.7 Steps:
1. Create a link https://ukr.net
2. Test it by clicking Visit link - it opens correctly
3. Save
4. Click on it and observe that the link is not shown in full - it's end is cut, that's why it points to wrong URL.
![image](https://user-images.githubusercontent.com/5199030/81113487-fc257b00-8f28-11ea-982b-17bf9d801131.png)

**Comment by te-online** [comment]
Hi @ostasevych, Sorry you're still having this issue. Let me try to reproduce with your detailed steps and I'll post my findings here.

**Comment by te-online** [comment]
I'm a bit confused, because I really can't reproduce this problem on my local testinstance.
See screencast here: https://te-cloud.de/index.php/s/KFjEQt7inDWoQJG

Can you share more screenshots or a screencast of how you create the link and if you browser console shows any errors?

Did you have the same problem on the latests stable version of nextcloud or is this something that started occurring only on version 19?

**Comment by ostasevych** [comment]
> I'm a bit confused, because I really can't reproduce this problem on my local testinstance.
> See screencast here: https://te-cloud.de/index.php/s/KFjEQt7inDWoQJG
> 
> Can you share more screenshots or a screencast of how you create the link and if you browser console shows any errors?
> 
> Did you have the same problem on the latests stable version of nextcloud or is this something that started occurring only on version 19?

Hi Thomas!

That's strange. Here is my screencast https://drive.google.com/file/d/116TghTPKY7HTomRtFNB634T08X0HV78g/view?usp=sharing

I use NC 19.0.7 beta.

**Comment by te-online** [comment]
> https://drive.google.com/file/d/116TghTPKY7HTomRtFNB634T08X0HV78g/view?usp=sharing

I don't seem to have access to the shared file, could you check the permissions? :-)

**Comment by te-online** [comment]
I just released a new version 1.1.0 for which I rewrote most of the client-side JS. Would you mind to check if the problem still exists? :-) Please re-open if it stills persists.
