### ISSUE TITLE
Special character are removed from the links

### ISSUE THREAD

**Issue by vfauth** [te-online/files_linkeditor#36]
Some special French characters like éèàù (probably some non-French too) are removed without warning when the link is saved.

This can be an issue with some websites.

Example  (saving then editing):
![saving](https://user-images.githubusercontent.com/32266846/86414031-1aa6b900-bcc3-11ea-9edb-a0ea6d878e91.png)
![editing](https://user-images.githubusercontent.com/32266846/86414039-1da1a980-bcc3-11ea-8fc1-b00f814c4047.png)

**Comment by te-online** [comment]
@vfauth Thanks for raising attention to this bug! This might be an issue with the sanitizer the app is using to make sure links follow the proper format.
