### ISSUE TITLE
Create or edit link in writeable shared folder

### ISSUE THREAD

**Issue by lazyandproud** [te-online/files_linkeditor#39]
Create or edit a link in a writeable shared Folder is not possible, but the option is present in the context menu.
![image](https://user-images.githubusercontent.com/58183116/95569093-62a54c80-0a25-11eb-9a98-7804628b7dd8.png)

**Comment by te-online** [comment]
Hey @lazyandproud Thanks for reporting. This does look like an annoying bug. I'll see if I can find some time soon to take a look at this :-)

**Comment by te-online** [comment]
It doesn't seem very straight forward to implement editing of files in editable shares, so I disabled editing for now. Please test again in `1.1.3`. 

Neither can I find an example of an app that can edit files when shared, nor any official documentation on it. If you find anything in that direction, feel free to reopen 😊 But as it stands right now, I don't know how can make it work in shared folders, so I'm going to close this.
