### ISSUE TITLE
Link Editor breaks Gallery

### ISSUE THREAD

**Issue by hasinasi** [te-online/files_linkeditor#4]
As soon as I enable Link Editor 1.0.3 in nc 13 gallery mode gets severely broken. Clicking on the icon showing the 4 tiles (to switch into thumbnail mode), nothing happens; the screen below the button just stays white. Similarly, the icon/button designed to be bringing you back into "normal" mode (smaller icons  on the left with file information) just does nothing. The only way to get back is to click the main icon of the "files" app, bringing you back to the root folder. 
Tried it on 2 machines, and this happens in 100% of the cases, and it goes immediately away, as soon as the Link Editor app is disabled. Otherwise the app works as expected.

**Comment by SimJoSt** [comment]
I observed the same exact behavior. It's a pity, as I would like to use this app, but the overwhelming amount of our users will prefer the gallery app :'(

**Comment by te-online** [comment]
Thanks for your reports! I'll fix this in the next version. I knew there was some kind of collision I hadn't fixed yet and this is the exact spot.

**Comment by te-online** [comment]
I could resolve an issue where the JavaScript would get loaded in wrong places and cause fatal JavaScript errors, resulting in side-effects on other scripts. Can you see if the problem still persists with version 1.0.4, as soon as the appstore offers it to you?

**Comment by hasinasi** [comment]
I just tested it, and as far as I can tell, the issue is fixed now! Thanks so much for looking into this and for fixing it!

**Comment by SimJoSt** [comment]
Same here. Everything works as expected.
Was surprised for a second, that I cannot edit on a left click, but have to go through the menu of the file.

**Comment by te-online** [comment]
> Was surprised for a second, that I cannot edit on a left click, but have to go through the menu of the file.

@SimJoSt Yes, this is a known UX-problem. I'll try to fix this in the next release. See #7.
