### ISSUE TITLE
Include Changelog into App Store listing

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [te-online/files_linkeditor#56]
It would be tremendously helpful to have the changelog included into the Nextcloud App Store listing. Currently, any (potentially breaking) changes must be fetched from this repository. Especially for production systems, a changelog at a glace in the app store listing might be helpful.

**Comment by te-online** [comment]
@TheOneWithTheBraid Thanks for raising this. Could you point me to an example where an app is doing this and how they format the changelog? I can see how this would be helpful to decide if an update is needed or not.

**Comment by te-online** [comment]
I think I got this covered now, please check out the app store listing of v1.1.7 🙌
