### ISSUE TITLE
incorrect newline/EOL in URL-files

### ISSUE THREAD

**Issue by DJCrashdummy** [te-online/files_linkeditor#6]
this is not really a big issue and i have no idea if it can be changed (easily)... but i noticed it, and maybe it is worth mentioning it:
the URL-files created with this awesome app have only a `LF` (unix-style) at the end of a line, while "original" URL-files created within windows have a `CR` and `LF` (windows-style).

if it is not clear what i am talking about, [this](https://en.wikipedia.org/wiki/Newline) and maybe [this](https://en.wikipedia.org/wiki/Text_file#Formats) will give enough background.

**Comment by te-online** [comment]
Thanks! I'll look into this.

**Comment by te-online** [comment]
I added a fix in 1.0.4 and I think it should fix the wrong line endings. Please let me know if the behavior changed as expected.

**Comment by DJCrashdummy** [comment]
@te-online yes, the newline-style looks good now.
but (no idea if this may be somewhere an issue - just want to mention it) after the link there is a `CR` `LF` resp. an empty new line missing, compared to original windows-links.

**Comment by te-online** [comment]
I can add a newline after the link, no problem ;-)
No idea if there is an RFC or something about that format...

**Comment by DJCrashdummy** [comment]
i'm pretty sure there is no RFC about "this (windows-)format"...!

but who knows... maybe someday after implementing some "cool new feature" by microsoft, the missing line will make this links incompatible. or maybe it is useful for regex...

**Comment by DJCrashdummy** [comment]
looks good now, @te-online. :+1: thank you!

it's only a pity that old links doesn't get converted... don't get me wrong, i'm NOT talking about scanning & converting all old links in general! but sadly if i modify a old link created by this app, they stay in the old format without a `CR` `LF` at the end. - thankfully other links (not created with this app and therefor already with a `CR` `LF`) are also kept as they are.
--> no idea, if it is worth the effort to add a check and convert old links at least after modification...

**Comment by te-online** [comment]
Thanks for testing! :-) Yeah, I thought about this, but dropped the thought, because I didn't want to mess with the stuff other applications might be doing to the end of the line and end of the file. Since I couldn't find a real standard for this document, I'm not sure how to implement it :-/

**Comment by DJCrashdummy** [comment]
no big deal! thank you, for writing this FOSS-app!

yes, these are also my thoughts... since there is no specification and no guarantee or even idea how some URL-files may look, it is better to not mess around with them. - at least in this case _"don't fix a running system"_. :wink: 

PS: i know it's off-topic, but a license-file somewhere (via github) beside the hint in the info.xml wouldn't hurt either.

**Comment by DJCrashdummy** [comment]
i wouldn't know anything to complain about! :wink:
