### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by Lurkars** [te-online/files_linkeditor#63]
No license information can be found for this repository. Please add a LICENSE/COPYING file.

**Comment by te-online** [comment]
@Lurkars Thanks for mentioning it. Would you mind pointing me to a good process of selecting and adding a license? I have no experience with that, unfortunately 😿

**Comment by Lurkars** [comment]
Hey, as stated out here under license
https://docs.nextcloud.com/server/latest/developer_manual//app_development/info.html 

> licence
>
>         required
> 
>         must contain agpl, mpl* and/or apache as the only valid values. These refer to the AGPLv3, MPL 2.0 and Apache License 2.0

In your info.xml you already stated out the AGPL license, so you can just put that licensee file to your repository. You can see an example here in official apps:
https://raw.githubusercontent.com/nextcloud/deck/master/LICENSE

**Comment by te-online** [comment]
Thanks! Should be added ✅
