### ISSUE TITLE
Compatibilty to Nextcloud 24

### ISSUE THREAD

**Issue by 42ske** [te-online/files_linkeditor#67]
Do you already know, when we will see a version compatible to Nextcloud 24? Thanks in advance.

**Comment by te-online** [comment]
Hi there 👋 Currently Nextcloud 24 is not yet available on the website, that's why I'd assume it's not finished yet. But I will prepare testing on version 24 during the upcoming weeks. You can expect an update of Linkeditor shortly after 24 is available from the Nextcloud website 😊
