### ISSUE TITLE
Use Transifex for continuous translation please

### ISSUE THREAD

**Issue by p-bo** [te-online/files_linkeditor#72]
Hello,
would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
...and gain benefits from work of whole Nextcloud translators community for users of your app please?

Thanks :-)

**Comment by te-online** [comment]
Great suggestion 👍 Since this seems to involve a couple of steps I will get back to it when I have some time to spare.

**Comment by p-bo** [comment]
Don't worry, it shouldn't take you much time - just open issue on https://github.com/nextcloud/docker-ci/issues/new/choose (choose Request translations). And you will get checklist as for example this: https://github.com/nextcloud/docker-ci/issues/426 and you can ask [rakekniven](https://github.com/rakekniven) if something is unclear to you. Hope it helps :-)

**Comment by p-bo** [comment]
For motivation: This developer at first [was not so fond](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1260663047) of this approach, than [he agreed to try](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1268635618) and at the end, [was very pleased](https://github.com/powerpaul17/nc_money/issues/4#issuecomment-1274590428) with result! :-)

**Comment by te-online** [comment]
@p-bo Thanks for your motivational message and helpful links 😊 

This is definitely on my list, and I'm not at all opposed to connecting Transifex. But as we already have a working way to add translations, unfortunately this doesn't have the highest priority right now. Hope you understand and can wait a little bit longer 😿

**Comment by p-bo** [comment]
@te-online I see and understand, that there are [more urgent things](https://help.nextcloud.com/u/te-online) in development of apps itself.

So will patiently wait until there will be resources to do (one time) work on adding support for _continuous_ translation then, as it will provide following benefits (for instance):

- much more translators will get involved, because without it, they will newer even know about possibility to translate this app - example of benefits for project known in this manner for community of Nextcloud translators (app with recently added to this workflow, based on same request as this one): https://github.com/H2CK/oidc/commit/937fc37d7797fecc9f4f49e12a154cd8987cf99c (see this and ongoing Nextcloud bot commits - translation of app is getting completed/improved in no time)
- also, as app is evolving, when some string(s) in app is/are changed/added, in case of continuous translation workflow translators are noticed intermediately and strings are translated before new version is released. In contrast with situation, that this change (in source strings) is only silently published in git repo and no one will (get) notice(d) till never version with untranslated strings get released (proactive vs retroactive).
- when one (of translators) will during using this app notice possibility to translate something in better manner, it is much efficient (especially for minor changes) to do this in translation tool than edit file directly in git. For example in case of one letter changes (misspelled words, etc.) has change directly in git such overhead (many steps to change just one letter), that these type of tweaks are rare due this (loss of quality for users)

To conclude: with _continuous_ translation workflow, result is, that users of your app are getting more complete and more polished localization, so their user experience is much more pleasant.

**Comment by comradekingu** [comment]
Transifex is the opposite of continuous translation workflow.
Use Weblate and thank me later. https://hosted.weblate.org/hosting/

**Comment by te-online** [comment]
Hey @p-bo, I have some more questions I'm hoping you'll be able to help me with 😊 

1. What happens to existing translations that are composed as `.json` and `.js` files in this repository? Do I need to convert them to `.pot` files or something like that?
2. How do I select the `lang_map` in the config file?

```
[main]
host     = https://www.transifex.com
lang_map = th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi, hu_HU: hu, nb_NO: nb, sk_SK: sk

[o:nextcloud:p:nextcloud:r:files_linkeditor]
file_filter = translationfiles/<lang>/files_linkeditor.po
source_file = translationfiles/templates/files_linkeditor.pot
source_lang = en
type        = PO
```

**Comment by p-bo** [comment]
Hey @te-online, yes of course (only limited by my abilities - as mere translator - to just point to hopefully useful resources and people connections)!
 
>     1. What happens to existing translations that are composed as `.json` and `.js` files in this repository? Do I need to convert them to `.pot` files or something like that?

Well, without any action, they would be (but only temporary! - we, translators, are tending to be agile ;-) ) lost, but it is possible to import pre-existing translations too - as was discussed and solved in this issue:
https://github.com/nextcloud/docker-ci/issues/471
 
>     2. How do I select the `lang_map` in the config file?

Not sure, if understood question, but this map is all about lang_CODE_on_Transifex:lang_code_in_app mapping - looking in content of transifex config files, created/corrected in repos of apps, mentioned in the end of this reply (successfully onboarded apps translations), this line seems to be (at least on first look) always the same.
(order is seems to be unimportant - see for example:
https://github.com/rotdrop/nextcloud-app-files-archive/blob/main/.tx/config
https://github.com/rotdrop/nextcloud-app-pdf-downloader/blob/main/.tx/config
https://github.com/julien-nc/integration_dropbox/blob/master/.tx/config
https://github.com/zorn-v/nextcloud-social-login/blob/master/.tx/config )
> ```
> [main]
> host     = https://www.transifex.com
> lang_map = th_TH: th, ja_JP: ja, bg_BG: bg, cs_CZ: cs, fi_FI: fi, hu_HU: hu, nb_NO: nb, sk_SK: sk
> 
> [o:nextcloud:p:nextcloud:r:files_linkeditor]
> file_filter = translationfiles/<lang>/files_linkeditor.po
> source_file = translationfiles/templates/files_linkeditor.pot
> source_lang = en
> type        = PO
> ```

But the most important message is, that when you open issue with request for integrating and try your best, maintainer(s) of this workflow are more than happy to answer detailed questions and even help trough pull requests to your repo with whole process, as you can see from communications (and mentioned apps repos commits) history in successfully onboarded translations of other apps. 

Helped this at least a bit regarding encouraging you to advance on this please? If needed, I can try to search/study more deeply to assist, but as translator, most effective contribution from me is maintaining translation(s) :-)

**Comment by te-online** [comment]
@p-bo Thank you so much for your response – it helps a ton. I'll get this sorted soon 👍

**Comment by te-online** [comment]
I will try and merge from the `translation` branch every once in a while 😊

**Comment by p-bo** [comment]
That's great - thanks for your commitment! :-) 
Was there success in finding workaround regarding .svelte files (https://github.com/nextcloud/docker-ci/issues/475#issuecomment-1345354222)?
Hope that advancements in translations contributions are worth and if yes and when your capacities will allow, looking (and other translators to ;-) ) to also regularly contribute translations to TimeManager (https://github.com/te-online/timemanager/issues/88) too. Have a nice day and thanks again :-)

**Comment by te-online** [comment]
No solution for scanning `.svelte` files. However, I keep a list of strings from those files in a separate `.js` file so we should be good.
