### ISSUE TITLE
Nextcloud 25 Support

### ISSUE THREAD

**Issue by Tealk** [te-online/files_linkeditor#73]
The tool does not seem to work under v25 anymore, neither can you create links nor edit them

![image](https://user-images.githubusercontent.com/12276250/195299073-721f2051-1925-4f7e-8bf9-fc00f0519c0a.png)

![image](https://user-images.githubusercontent.com/12276250/195299011-9127171b-402d-497a-8f88-8b3cd27a7592.png)

**Comment by Tealk** [comment]
Somehow the addon was activated only after pressing enable a second time.

**Comment by te-online** [comment]
Hey there 👋 Thanks for reporting! Indeed NC 25 is not marked as supported in appinfo.xml yet. This is why you had to manually enable it. I will re-open this issue, so I don't forget to switch end-to-end tests to 25 and release a new version.

**Comment by JimKillock** [comment]
Quick query when we might have NC 25 support rolled out :) We have had to disable to app for now but would really like to have it back :)

**Comment by te-online** [comment]
I've published a new version that is marked as compatible with NC 25. End-to-end tests have passed.
