### ISSUE TITLE
l10n: Remove unwanted strings from Transifex

### ISSUE THREAD

**Issue by rakekniven** [te-online/files_linkeditor#75]
The following two strings do not need to get translated.

https://github.com/te-online/files_linkeditor/blob/eee7bf68dbb71a66f6cf0bc29e80f5d293b8f7c0/js/lib/Linkeditor.service.js#L93

https://github.com/te-online/files_linkeditor/blob/eee7bf68dbb71a66f6cf0bc29e80f5d293b8f7c0/js/lib/Linkeditor.service.js#L98

**Comment by te-online** [comment]
Are you sure about that? 🙂 My thinking was that maybe not every language calls a "link" a "Link"? Since this is the default filename for new files when clicking the + on the files app. But maybe I'm wrong there.

**Comment by te-online** [comment]
Thanks for clarifying. I added the comment, hope it's going to propagate. Let me know if there's more. 

I will try and investigate now why transifex is not recognizing a lot of translations and how I can import existing translations...
