### ISSUE TITLE
When you enable the app you cannot edit "additional settings" anymore.

### ISSUE THREAD

**Issue by danielepercivaldi** [te-online/files_linkeditor#8]
NC 13.0.0
Ubuntu 16.04 LTS 64 bit
PHP7.0
MySQL 14.14
When you enable the app Link Editor "additional settings" section stops working (cannot change settings or save or send email test, etc.)

**Comment by te-online** [comment]
Thanks for reporting. Will look into that!

**Comment by te-online** [comment]
I could resolve an issue where the JavaScript would get loaded in wrong places and cause fatal JavaScript errors, resulting in side-effects on other scripts. Can you see if the problem still persists with version 1.0.4, as soon as the appstore offers it to you?

**Comment by danielepercivaldi** [comment]
Hi.
Now it's ok.

Thanks.
