### ISSUE TITLE
Make this app compatible with NC26

### ISSUE THREAD

**Issue by joergmschulz** [te-online/files_linkeditor#80]
compatibility is set to 25
see here https://help.nextcloud.com/t/any-apps-not-compatible-with-nextcloud-26/155950

**Comment by te-online** [comment]
Thanks for reporting – I can see we now have a 26 docker tag, so I will run end-to-end tests and prepare a new release soon 😊

**Comment by te-online** [comment]
Should be fixed in v1.1.14
