### ISSUE TITLE
error 404 on creation

### ISSUE THREAD

**Issue by pierreozoux** [te-online/files_linkeditor#94]
Hi,

we are running version 1.1.16 on Nc 27.1.7.
And we have a 404 when we try to create a new URL file.

We use postgres for DB and minio for ObjectStore.

Here is a screenshot:
![Screenshot 2024-03-06 at 14-03-45 Files - Nuage Liiibre](https://github.com/te-online/files_linkeditor/assets/1863453/cc975ea6-fee3-4415-99d7-e8f1cb5d8f34)

Request headers:
```
GET /apps/files_linkeditor/ajax/loadfile?filename=test333333eeee.URL&dir=%2F HTTP/2
Host: nuage.xxx
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
requesttoken: x=
DNT: 1
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=x; nc_token=x; nc_session_id=x; oc_sessionPassphrase=xTE: trailers
```
Response headers
```
HTTP/2 404 
date: Wed, 06 Mar 2024 13:03:30 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
cache-control: no-cache, no-store, must-revalidate
x-request-id: BSuApYYRIMXmNxoa4hCe
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'x=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self';frame-src 'self' data:;child-src 'self';frame-ancestors 'self';form-action 'self'
feature-policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: noindex, nofollow, noindex, nofollow
x-xss-protection: 1; mode=block
strict-transport-security: max-age=15724800; includeSubDomains
content-encoding: br
X-Firefox-Spdy: h2
```

Checking the PUT operations, it looks fine with a 201 response. the thing that look strange to me is that the request payload is empty.

Anybody can reproduce?

Thanks for your effort and help,

Have a nice day!

**Comment by te-online** [comment]
Thanks for opening an issue. We had a similar issue before where it seemed like eventual consistency of the filesystem was the issue if I remember correctly. Could that be the case for you? 

- If you create another type of file and try to load it immediately after, does it also fail with 404? (Maybe try using Curl or similar to simulate it)
- Can you eventually (after a while) open your link file or does it stay 404 forever?

The reason for the `PUT` being empty is that it merely creates the file. The content is being added by a second request to the `savefile` endpoint.

The flow is as follows:
1. The file is creating using the `menu.fileList` API
2. The file is being loaded using the app's API
3. The contents are written to the empty file using the app's API

**Comment by pierreozoux** [comment]
It stays forever 404.

And minio should be consistent:
https://github.com/minio/minio/blob/master/docs/distributed/README.md#consistency-guarantees

In my browser I see these 3 calls:
```
curl 'https://nuage.liiib.re/remote.php/dav/files/pierreok/tmp/test.URL' -X PUT -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: text/plain' -H 'X-Requested-With: XMLHttpRequest' -H 'requesttoken: x=' -H 'Origin: https://nuage.liiib.re' -H 'DNT: 1' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'If-None-Match: *' -H 'Connection: keep-alive' -H 'Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=pierreok; nc_token=x; nc_session_id=x; oc_sessionPassphrase=x' -H 'TE: trailers' --data-raw ' '

201

curl 'https://nuage.liiib.re/remote.php/dav/files/pierreok/tmp/test.URL' --compressed -X PROPFIND -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/xml; charset=utf-8' -H 'Content-Length: 704' -H 'X-Requested-With: XMLHttpRequest' -H 'requesttoken: x=' -H 'Depth: 0' -H 'Origin: https://nuage.liiib.re' -H 'DNT: 1' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Connection: keep-alive' -H 'Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=pierreok; nc_token=x; nc_session_id=x; oc_sessionPassphrase=x' -H 'TE: trailers'

207

curl 'https://nuage.liiib.re/apps/files_linkeditor/ajax/loadfile?filename=test.URL&dir=%2Ftmp' --compressed -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'requesttoken: x=' -H 'DNT: 1' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Connection: keep-alive' -H 'Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=pierreok; nc_token=x; nc_session_id=x; oc_sessionPassphrase=x' -H 'TE: trailers'
```

And the last one is a 404, at creation time and at "read" time later. Yes, indeed it is strange, as I see it in the UI, so "the file is there" somehow..

I don't know what to give you more to help you debug. On my side, it is not a high priority, so it is more something to help the next one that has the same bug.

**Comment by te-online** [comment]
Hm... Okay, so your Nextcloud uses Object Storage? That might be the reason. Maybe the fileList API doesn't wait for the object to be fully created in object storage, but it's only in Nextcloud's database.

I will have to rewrite the entire app for Nextcloud 28 anyways, so I hope to fix this issue there. A workaround could be to retry when getting a 404, so the app can successfully write to the file and it won't be empty.
